//
//  Bot.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import <Foundation/Foundation.h>
#import <AWSCore/AWSCore.h>

NS_ASSUME_NONNULL_BEGIN

/**
 *  Represents the configuration for a Bot created with Amazon Lex.
 */
@interface BotConfiguration : NSObject

// Name of the bot
@property (nonatomic, readonly) NSString *name;

// Alias of the bot
@property (nonatomic, readonly) NSString *alias;

// Region where the bot is created
@property (nonatomic, readonly) AWSRegionType region;

/**
 *  Initializer for BotConfiguration object
 *
 *  @param botName   name of the bot
 *  @param botAlias  alias of the bot
 *  @param botRegion region where bot was created
 *
 *  @return instance of BotConfiguration with specified configuration
 */
-(instancetype)initWithBotName:(NSString *)botName
                      botAlias:(NSString *)botAlias
                     botRegion:(AWSRegionType)botRegion;

@end

/**
 *  Represense a bot created with Amazon Lex.
 */
@interface Bot : NSObject

// Name of the Bot
@property (nonatomic, readonly) NSString *name;

// Description for the bot
@property (nonatomic, readonly, nullable) NSString *botDescription;

// Intents (Commands) available for the bot
@property (nonatomic, readonly, nullable) NSArray<NSString *> *commandsHelp;

// Configuration for the bot
@property (nonatomic, readonly) BotConfiguration *configuration;

/**
 *  Initializer for bot object
 *
 *  @param botName          name for the bot
 *  @param botDescription   description for the bot
 *  @param botCommandsHelp  intents (commands) availabe for the bot
 *  @param botConfiguration the configuration object for the bot
 *
 *  @return an instance of Bot with specified parameters
 */
-(instancetype)initWithBotName:(NSString *)botName
                botDescription:(NSString *)botDescription
                  commandsHelp:(NSArray<NSString *> *)botCommandsHelp
              botConfiguration:(BotConfiguration *)botConfiguration;

@end

NS_ASSUME_NONNULL_END
