//
//  Bot.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import "Bot.h"

@interface BotConfiguration()

@property (nonatomic, readwrite) NSString *name;
@property (nonatomic, readwrite) NSString *alias;
@property (nonatomic, readwrite) AWSRegionType region;

@end

@interface Bot()

@property (nonatomic, readwrite) NSString *name;
@property (nonatomic, readwrite) NSString *botDescription;
@property (nonatomic, readwrite) NSString *identifier;
@property (nonatomic, readwrite) NSArray<NSString *> *commandsHelp;

@end

@implementation Bot

-(instancetype)initWithBotName:(NSString *)botName
                botDescription:(NSString *)botDescription
                  commandsHelp:(NSArray<NSString *> *)botCommandsHelp
              botConfiguration:(BotConfiguration *)configuration{
    
    if (self = [super init]) {
        _name = botName;
        _botDescription = botDescription;
        _commandsHelp = botCommandsHelp;
        _configuration = configuration;
    }
    return self;
}

@end

@implementation BotConfiguration

-(instancetype)initWithBotName:(NSString *)botName
                      botAlias:(NSString *)botAlias
                     botRegion:(AWSRegionType)botRegion {
    if (self = [super init]) {
        _name = botName;
        _alias = botAlias;
        _region = botRegion;
    }
    return self;
}

@end
