//
//  BotOperationsViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import "BotOperationsViewController.h"
#import "Bot.h"
#import "BotTextChatViewController.h"
#import "BotVoiceChatViewController.h"
@import JSQMessagesViewController;

@interface BotOperationsViewController()

@property (nonatomic, strong) Bot *bot;
@property (nonatomic, strong) NSArray<NSString *> *botCommandsList;
@property (nonatomic, strong) NSArray<NSString *> *conversationTypes;

@end

@interface BotTextChatViewController()

@property (nonatomic, readwrite) NSString *botName;
@property (nonatomic, readwrite) NSString *botAlias;
@property (nonatomic, readwrite) AWSRegionType botRegion;

@end

@interface BotVoiceChatViewController()

@property (nonatomic, strong) Bot *bot;

@end

@implementation BotOperationsViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.conversationTypes = @[@"Voice to Voice Demo", @"Text to Text Demo"];
    self.botDescription.text = self.bot.botDescription;
    self.botCommandsList = self.bot.commandsHelp;
    self.title = self.bot.name;
    if(self.botCommandsList.count == 0) {
        self.botCommands.hidden = true;
        self.botIntentsLabel.hidden = true;
    }
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    if ( tableView == self.botCommands) {
        return self.botCommandsList.count;
    } else {
        return self.conversationTypes.count;
    }
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    
    if ( tableView == self.botCommands) {
        UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"CommandCellIdentifier" forIndexPath:indexPath];
        cell.textLabel.numberOfLines = 0;
        cell.textLabel.lineBreakMode = NSLineBreakByWordWrapping;
        cell.textLabel.font = [UIFont italicSystemFontOfSize:(14.0)];
        cell.textLabel.text = [NSString stringWithFormat:@"\"%@\"", self.botCommandsList[indexPath.row]];
        return cell;
    } else {
        UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"OperationTypeCellIdentifier" forIndexPath:indexPath];
        cell.textLabel.text = self.conversationTypes[indexPath.row];
        cell.textLabel.textColor = [UIColor jsq_messageBubbleBlueColor];
        cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
        return cell;
    }
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(nonnull NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    if ( tableView == self.conversationTypesList) {
        if (indexPath.row == 0) {
            UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"BotVoiceChat"
                                                                 bundle:nil];
            BotVoiceChatViewController *voiceChatViewController = (BotVoiceChatViewController *)[storyboard instantiateViewControllerWithIdentifier:@"BotVoiceChat"];
            voiceChatViewController.bot = self.bot;
            [self.navigationController pushViewController:voiceChatViewController animated:YES];
        } else {
            UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"BotTextChat"
                                                                 bundle:nil];
            BotTextChatViewController *botTextChatViewController = (BotTextChatViewController *)[storyboard instantiateViewControllerWithIdentifier:@"BotTextChat"];
            botTextChatViewController.botName = self.bot.configuration.name;
            botTextChatViewController.botRegion = self.bot.configuration.region;
            botTextChatViewController.botAlias = self.bot.configuration.alias;
            [self.navigationController pushViewController:botTextChatViewController animated:YES];
        }
    }
}

@end
