//
//  BotOperationsViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import <UIKit/UIKit.h>

/**
 *  Shows a list of operations possible with a bot(text converstion / voice conversation)
 */
@interface BotOperationsViewController : UIViewController<UITableViewDataSource, UITableViewDataSource>

// Description for the bot
@property (weak, nonatomic) IBOutlet UILabel *botDescription;

// Types of conversation supported with bot (text / voice)
@property (weak, nonatomic) IBOutlet UITableView *conversationTypesList;

// Intents (commands) supported by Bot
@property (weak, nonatomic) IBOutlet UITableView *botCommands;

// Label for bot intents
@property (weak, nonatomic) IBOutlet UILabel *botIntentsLabel;

@end
