//
//  BotsFactory.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import <Foundation/Foundation.h>
#import "Bot.h"

/**
 *  Manages list of bots available for Demo in the sample app
 */
@interface BotsFactory : NSObject

/**
 *  Fetches the list of bots configured through Mobile Hub Console
 *
 *  @return the list of bots configured through Mobile Hub
 */
+ (NSArray<Bot *> *)supportedBots;

@end
