//
//  BotsLandingViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import <UIKit/UIKit.h>

/**
 *  The landing screen for showing the list of bots available for Demo.
 */
@interface BotsLandingViewController : UIViewController<UITableViewDelegate, UITableViewDataSource>

// List of bots available for demo
@property (weak, nonatomic) IBOutlet UITableViewController *botsListTableView;

@end
