//
//  BotsFactory.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
#import "BotsFactory.h"
#import "AWSConfiguration.h"

@implementation BotsFactory

+ (NSArray<Bot *> *)supportedBots {
    
    return @[
                [[Bot alloc] initWithBotName:@"SearchObjects"
                              botDescription:@""
                                commandsHelp:@[
                                               ]

                            botConfiguration:[[BotConfiguration alloc] initWithBotName:SearchObjectsBotName
                                                  botAlias:SearchObjectsBotAlias
                                                 botRegion:SearchObjectsBotRegion]],
             ];
}

@end
