//
//  BotsLandingViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import "BotsLandingViewController.h"
#import "Bot.h"
#import "BotsFactory.h"
#import "BotOperationsViewController.h"
@import JSQMessagesViewController;

@interface BotsLandingViewController()

@property (nonatomic, strong) NSArray<Bot *> *bots;

@end

@interface BotOperationsViewController()

@property (nonatomic, strong) Bot *bot;
@property (nonatomic, strong) NSArray<NSString *> *botCommandsList;
@property (nonatomic, strong) NSArray<NSString *> *conversationTypes;

@end

@implementation BotsLandingViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Back"
                                                                             style:UIBarButtonItemStylePlain
                                                                            target:nil
                                                                            action:nil];
    self.bots = [BotsFactory supportedBots];
    
    
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return [self.bots count];
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 1;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"BotsListTableCell" forIndexPath:indexPath];
    
    Bot *bot = self.bots[indexPath.section];
    cell.textLabel.text = bot.name;
    cell.textLabel.textColor = [UIColor jsq_messageBubbleBlueColor];
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    
    static NSString *showQueryResultSeque = @"BotShowDetailsSegue";
    [self performSegueWithIdentifier:showQueryResultSeque sender:self.bots[indexPath.section]];
}

-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    if ([segue.destinationViewController isKindOfClass:[BotOperationsViewController class]]) {
        BotOperationsViewController *botOperations = (BotOperationsViewController *)segue.destinationViewController;
        botOperations.bot = (Bot *)sender;
    }
}

@end
