//
//  BotVoiceChatViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import <UIKit/UIKit.h>
#import <AWSLex/AWSLex.h>

/**
 *  Manages a voice-to-voice conversation with a bot
 */
@interface BotVoiceChatViewController : UIViewController

// The AWS Lex Voice Button for voice-to-voice interaction
@property (weak, nonatomic) IBOutlet AWSLexVoiceButton *voiceButton;

// Label to show any text output
@property (weak, nonatomic) IBOutlet UILabel *output;

// The AWS Lex Voice Button Delegate
@property (nonatomic, weak) id<AWSLexVoiceButtonDelegate> delegate;

@end
