//
//  BotVoiceChatViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//

#import "BotVoiceChatViewController.h"
#import "AWSConfiguration.h"
#import "Bot.h"
#import <AWSMobileHubHelper/AWSMobileHubHelper.h>
#import <AWSLex/AWSLex.h>

@interface BotVoiceChatViewController()<AWSLexVoiceButtonDelegate>

@property (nonatomic, strong) Bot *bot;

@end

@implementation BotVoiceChatViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    // Set the bot configuration details
    NSString *botName = self.bot.configuration.name;
    NSString *botAlias = self.bot.configuration.alias;
    AWSRegionType botRegion = self.bot.configuration.region;
    
    // set up the configuration for AWS Voice Button
    AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:botRegion credentialsProvider: [AWSIdentityManager defaultIdentityManager].credentialsProvider];
    AWSLexInteractionKitConfig *interactionConfig = [AWSLexInteractionKitConfig defaultInteractionKitConfigWithBotName:botName botAlias:botAlias];
    
    // register the interaction kit client for the voice button using the `AWSLexVoiceButtonKey` constant defined in SDK
    [AWSLexInteractionKit registerInteractionKitWithServiceConfiguration:serviceConfiguration interactionKitConfiguration:interactionConfig forKey:AWSLexVoiceButtonKey];
    
    // set the voice button delegate
    self.voiceButton.delegate = self;
    
    // Do any additional setup after loading the view, typically from a nib.
}

#pragma mark - VoiceButtonDelegate Methods

- (void)voiceButton:(AWSLexVoiceButton *)button onResponse:(AWSLexVoiceButtonResponse *)response {
    NSLog(@"on text output %@", response.outputText);
    self.output.text = response.outputText;
}

- (void)voiceButton:(AWSLexVoiceButton *)button onError:(NSError *)error{
    NSLog(@"error %@", error);
}

@end
