//
//  UserIdentityViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
#import "UserIdentityViewController.h"
#import <AWSMobileHubHelper/AWSMobileHubHelper.h>

@interface UserIdentityViewController ()

@end

@implementation UserIdentityViewController

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    AWSIdentityManager *identityManager = [AWSIdentityManager defaultIdentityManager];

    if (identityManager.identityProfile.userName) {
        self.userName.text = identityManager.identityProfile.userName;
    } else {
        self.userName.text = NSLocalizedString(@"GUEST USER", @"Placeholder text for the guest user.");
    }
    self.userID.text = identityManager.identityId;
    NSURL *imageUrl = identityManager.identityProfile.imageURL;

    NSData *imageData = [NSData dataWithContentsOfURL:imageUrl];
    UIImage *profileImage = [UIImage imageWithData:imageData];
    if (profileImage) {
        self.userImageView.image = profileImage;
    } else {
        self.userImageView.image = [UIImage imageNamed:@"UserIcon"];
    }
}

@end
