//
//  AWSConfiguration.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
//

#import "AWSConfiguration.h"


// Name of SearchObjects bot
NSString *const SearchObjectsBotName = @"SearchObjects";
// Alias for SearchObjects bot
NSString *const SearchObjectsBotAlias = @"$LATEST";
// Region for SearchObjects bot
AWSRegionType const SearchObjectsBotRegion = AWSRegionUSEast1;
