//
//  AWSConfiguration.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
//

#import <Foundation/Foundation.h>
#import <AWSCore/AWSCore.h>

// Configuration for Bots

FOUNDATION_EXPORT NSString *const SearchObjectsBotName;
FOUNDATION_EXPORT NSString *const SearchObjectsBotAlias;
FOUNDATION_EXPORT AWSRegionType const SearchObjectsBotRegion;
